// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentReadiness(arg1) {
  return window['go']['main']['App']['AgentReadiness'](arg1);
}

export function CancelDiagnostic(arg1) {
  return window['go']['main']['App']['CancelDiagnostic'](arg1);
}

export function CompleteDiagnostic(arg1) {
  return window['go']['main']['App']['CompleteDiagnostic'](arg1);
}

export function ConfigurationPath() {
  return window['go']['main']['App']['ConfigurationPath']();
}

export function ConfigureModel(arg1) {
  return window['go']['main']['App']['ConfigureModel'](arg1);
}

export function ConversationApprovalEnabled(arg1) {
  return window['go']['main']['App']['ConversationApprovalEnabled'](arg1);
}

export function ConversationEvents(arg1) {
  return window['go']['main']['App']['ConversationEvents'](arg1);
}

export function Conversations(arg1) {
  return window['go']['main']['App']['Conversations'](arg1);
}

export function CurrentConversation(arg1) {
  return window['go']['main']['App']['CurrentConversation'](arg1);
}

export function DatabasePath() {
  return window['go']['main']['App']['DatabasePath']();
}

export function DiagnosticEvents(arg1) {
  return window['go']['main']['App']['DiagnosticEvents'](arg1);
}

export function DiagnosticRun(arg1) {
  return window['go']['main']['App']['DiagnosticRun'](arg1);
}

export function Emit(arg1) {
  return window['go']['main']['App']['Emit'](arg1);
}

export function ExecuteManualTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteManualTool'](arg1, arg2, arg3);
}

export function GenerateManualDraft(arg1) {
  return window['go']['main']['App']['GenerateManualDraft'](arg1);
}

export function ModelSettings() {
  return window['go']['main']['App']['ModelSettings']();
}

export function NewConversation(arg1) {
  return window['go']['main']['App']['NewConversation'](arg1);
}

export function OpenConversation(arg1, arg2) {
  return window['go']['main']['App']['OpenConversation'](arg1, arg2);
}

export function ResolveApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveApproval'](arg1, arg2, arg3);
}

export function SaveTargetProfile(arg1) {
  return window['go']['main']['App']['SaveTargetProfile'](arg1);
}

export function StartDiagnostic(arg1) {
  return window['go']['main']['App']['StartDiagnostic'](arg1);
}

export function StartManualSession(arg1) {
  return window['go']['main']['App']['StartManualSession'](arg1);
}

export function TargetProfiles() {
  return window['go']['main']['App']['TargetProfiles']();
}

export function ToolDefinitions() {
  return window['go']['main']['App']['ToolDefinitions']();
}
