// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {tools} from '../models';

export function AgentReadiness(arg1:string):Promise<domain.AgentReadiness>;

export function CancelDiagnostic(arg1:string):Promise<domain.Run>;

export function CompleteDiagnostic(arg1:string):Promise<domain.Run>;

export function ConfigurationPath():Promise<string>;

export function ConfigureModel(arg1:domain.ModelSettings):Promise<domain.ModelSettingsSummary>;

export function ConversationApprovalEnabled(arg1:string):Promise<boolean>;

export function ConversationEvents(arg1:string):Promise<Array<domain.Event>>;

export function Conversations(arg1:string):Promise<Array<domain.Conversation>>;

export function CurrentConversation(arg1:string):Promise<domain.Conversation>;

export function DatabasePath():Promise<string>;

export function DiagnosticEvents(arg1:string):Promise<Array<domain.Event>>;

export function DiagnosticRun(arg1:string):Promise<domain.Run>;

export function Emit(arg1:domain.Event):Promise<void>;

export function ExecuteManualTool(arg1:string,arg2:string,arg3:string):Promise<domain.Evidence>;

export function GenerateManualDraft(arg1:domain.ManualDraftRequest):Promise<domain.ManualDraftResponse>;

export function ModelSettings():Promise<domain.ModelSettingsSummary>;

export function NewConversation(arg1:string):Promise<domain.Conversation>;

export function OpenConversation(arg1:string,arg2:string):Promise<domain.Conversation>;

export function ResolveApproval(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SaveTargetProfile(arg1:domain.TargetProfile):Promise<domain.TargetProfileSummary>;

export function StartDiagnostic(arg1:domain.DiagnosticRequest):Promise<domain.Run>;

export function StartManualSession(arg1:string):Promise<domain.Run>;

export function TargetProfiles():Promise<Array<domain.TargetProfileSummary>>;

export function ToolDefinitions():Promise<Array<tools.Definition>>;
